import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import worker from '../backend/worker.js';
const origin='https://juldigi0107.github.io';
function environment(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../backend/migrations/0001_initial.sql',import.meta.url),'utf8'));return {ADMIN_TOKEN:'test-admin-not-a-production-secret',VIEWER_TOKEN:'test-viewer-not-a-production-secret',ALLOWED_ORIGINS:origin,DB:{prepare(sql){let args=[];const stmt=sqlite.prepare(sql);return {bind(...a){args=a;return this;},async first(){return stmt.get(...args);},async run(){const r=stmt.run(...args);return{meta:{changes:Number(r.changes)}};}};}},close:()=>sqlite.close()};}
const req=(path,{token='test-admin-not-a-production-secret',method='GET',data,rev='0',from=origin}={})=>new Request('https://worker.test/api/'+path,{method,headers:{Origin:from,Authorization:'Bearer '+token,'Content-Type':'application/json','If-Match':rev},body:data===undefined?undefined:JSON.stringify(data)});
const fixture=()=>({schemaVersion:1,source:{type:'DWG',file:'TEST_ONLY.dwg',sha256:'b'.repeat(64),extractionMethod:'Unit-test synthetic geometry; never shipped as factory'},transform:{sourceUnits:'m',scale:1,originX:0,originY:0,rotation:0},entities:[]});
test('authentication required and origin allowlist enforced',async()=>{const env=environment();assert.equal((await worker.fetch(req('state',{token:''}),env)).status,401);assert.equal((await worker.fetch(req('state',{from:'https://evil.test'}),env)).status,403);env.close();});
test('viewer can read but cannot mutate layout or position',async()=>{const env=environment(),token=env.VIEWER_TOKEN;assert.equal((await worker.fetch(req('state',{token}),env)).status,200);assert.equal((await worker.fetch(req('layout',{token,method:'PUT',data:fixture()}),env)).status,403);env.close();});
test('position cannot be saved before DWG-derived layout exists',async()=>{const env=environment();assert.equal((await worker.fetch(req('position',{method:'PUT',data:{x:0,y:0,z:0,rotation:0,scale:1,confidence:'APPROXIMATE'}}),env)).status,400);env.close();});
test('layout + position persist in SQLite and revision conflicts prevent lost updates',async()=>{const env=environment();let r=await worker.fetch(req('layout',{method:'PUT',data:fixture()}),env);assert.equal(r.status,200);assert.equal((await r.json()).revision,1);r=await worker.fetch(req('position',{method:'PUT',rev:'1',data:{x:125,y:3,z:25,rotation:30,scale:1,confidence:'USER-CONFIRMED'}}),env);assert.equal(r.status,200);const s=await (await worker.fetch(req('state'),env)).json();assert.equal(s.asset.layout_x,125);assert.equal(s.revision,2);assert.equal((await worker.fetch(req('position',{method:'DELETE',rev:'1'}),env)).status,409);assert.equal((await worker.fetch(req('position',{method:'DELETE',rev:'2'}),env)).status,200);const reset=await (await worker.fetch(req('state'),env)).json();assert.equal(reset.asset.layout_x,null);assert.equal(reset.asset.positionConfidence,'UNKNOWN');env.close();});
test('unconfigured DB cannot claim saved data',async()=>{const env=environment();env.DB=null;assert.equal((await worker.fetch(req('state'),env)).status,503);env.close();});
test('invalid JSON is actionable, CORS preflight has allowed headers',async()=>{const env=environment();const request=new Request('https://worker.test/api/layout',{method:'PUT',headers:{Origin:origin,Authorization:'Bearer '+env.ADMIN_TOKEN,'If-Match':'0','Content-Type':'application/json'},body:'{broken'});assert.equal((await worker.fetch(request,env)).status,400);const r=await worker.fetch(new Request('https://worker.test/api/state',{method:'OPTIONS',headers:{Origin:origin}}),env);assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),origin);env.close();});
