import {FactoryEngine} from './src/engine.js';
import {initialState,validateLayout,validatePosition,worldToCad} from './src/model.js';
import {OFFSET5_TAXONOMY,TAXONOMY_BY_ID,taxonomyChildren,taxonomyStats} from './src/data/taxonomy-offset5.js';
import {PHOTO_REGISTRY,TECHNICAL_SOURCES,photoStats,ORIENTATION} from './src/data/sources-offset5.js';
import {confidenceLabel} from './src/data/confidence.js';
import {loadBundledPlantLayout,drawPlantPlan} from './src/data/plant-layout-data.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'UNKNOWN').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>Number.isFinite(n)?n.toLocaleString('id-ID',{maximumFractionDigits:4}):'UNKNOWN';
let state=structuredClone(initialState),engine,activeTab='overview',apiBase='',token='',role=null,editing=false,explode=0,selectedPart=null,selectedTaxonomyId='O5',toastTimer,bundledLayout=null;
const toast=(message,error=false)=>{clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.toggle('error',error);$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,error?9000:5000);};
const safe=fn=>async(...args)=>{try{await fn(...args);}catch(e){toast(e.message,true);}};
const on=(id,fn)=>$(id).addEventListener('click',safe(fn));
function modal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function showPanel(){document.body.classList.remove('panel-hidden');}
const activeLayout=()=>state.layout||bundledLayout;
function redrawPlantPlan(){if(bundledLayout)drawPlantPlan($('#dwg-canvas'),bundledLayout);}
function pair(label,value){return `<dt>${esc(label)}</dt><dd${value==null?' class="unknown"':''}>${esc(value)}</dd>`;}
function choosePart(part){if(!part||!engine)return;engine.template.reset();engine.isolated=false;explode=0;selectedPart=part;engine.template.highlight(part);engine.fit(part);}
function taxonomyTree(parentId='O5'){
 const children=taxonomyChildren(parentId);return children.map(n=>{const descendants=taxonomyChildren(n.id);const mapped=!!engine?.template.resolveTaxonomyNode(n.id);return `<div class="geometry-node"><button data-taxonomy="${esc(n.id)}" aria-pressed="${n.id===selectedTaxonomyId}" title="${esc(confidenceLabel(n.confidence))}">${esc(n.name)} <span class="tax-level">L${n.level}${mapped?' · 3D':' · META'}</span></button>${descendants.length?`<details ${selectedTaxonomyId.startsWith(n.id)?'open':''}><summary>${esc(n.levelName)}</summary>${taxonomyTree(n.id)}</details>`:''}</div>`;}).join('');
}
function renderPanel(tab=activeTab){if(editing&&engine){engine.edit(false);engine.onTransform=null;engine.applyPlacement(state);editing=false;}activeTab=tab;$$('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));const a=state.asset;
 if(tab==='overview'){
 $('#panel-content').innerHTML=`<h3>Identitas mesin</h3><dl class="data-list">${pair('Kode aset',a.asset_code)+pair('Manufacturer',a.manufacturer)+pair('Model',a.model)+pair('Kategori','Mesin produksi')+pair('Spesifikasi',a.specification)+pair('Lokasi',a.location)+pair('Status operasi',null)}</dl><h3>Representasi 3D</h3><div class="card accent"><h4>Rekonstruksi dari 9 foto aktual</h4><p>Feeder, cover melengkung, kisi roller, bak tinta, tangga, platform, dan delivery mengikuti ciri yang terlihat pada foto. Ukuran serta jarak antarbagian masih perkiraan.</p><span class="tag">APPROXIMATE</span><span class="tag">LOD 1</span></div><dl class="data-list">${pair('Dimensi aktual',null)+pair('Konfigurasi unit','8 housing visual · perlu verifikasi')+pair('Posisi',a.positionConfidence==='UNKNOWN'?'POSITION REVIEW REQUIRED':a.positionConfidence)+pair('Sumber identitas',a.sources.length+' dokumen')+pair('Verifikasi independen','Belum dilakukan')}</dl><div class="card"><h4>Fondasi berbasis bukti</h4><p>Bentuk luar bersumber dari foto. Delapan housing adalah susunan rekonstruksi visual; jumlah unit, coating, dryer, dan komponen internal tetap memerlukan bukti teknis.</p></div>`;
 }else if(tab==='structure'){
 const meta=TAXONOMY_BY_ID.get(selectedTaxonomyId)||TAXONOMY_BY_ID.get('O5'),stats=taxonomyStats();
 $('#panel-content').innerHTML=`<h3>Taxonomy mesin · 6 tahap</h3><p class="subtle">Tree teknis dipisahkan dari mesh. Label <b>3D</b> berarti sudah terhubung ke geometry luar; <b>META</b> berarti referensi teknis tanpa geometry yang diklaim aktual.</p><button id="tree-root" class="secondary">OFFSET 5 · L1 Mesin</button><div class="card accent" style="margin-top:12px"><h4>${esc(meta.name)}</h4><p>${esc(meta.description||'Node taxonomy teknik dengan provenance dan confidence eksplisit.')}</p><span class="tag">L${meta.level} · ${esc(meta.levelName)}</span><span class="tag">${esc(confidenceLabel(meta.confidence))}</span><p>${esc(meta.sourceRefs.join(', '))}</p></div><label for="explode">Explode visual <span id="explode-value">${Math.round(explode*100)}%</span></label><input id="explode" type="range" min="0" max="1" step="0.01" value="${explode}" ${engine?.view==='factory'?'disabled':''}><div class="actions"><button id="assemble" class="secondary">Rakit Kembali</button><button id="ghost" class="secondary ${engine?.template.ghosted?'active':''}">Transparansi</button><button id="isolate" class="secondary ${engine?.isolated?'active':''}" ${selectedPart?'':'disabled'}>Isolasi</button></div><div class="stage-strip">${[1,2,3,4,5,6].map(level=>`<button data-stage="${level}" class="${meta.level===level?'active':''}">L${level}</button>`).join('')}</div><div class="geometry-tree">${taxonomyTree()}</div><p class="subtle">${stats.total} node metadata. Detail internal dari manual/web tetap REFERENCE_ONLY sampai cocok dengan foto, serial, atau drawing mesin aktual.</p>`;
 $('#explode').addEventListener('input',e=>{explode=+e.target.value;engine?.template.explode(explode,selectedPart);if(selectedPart)engine.template.ghost(explode>0,selectedPart);$('#explode-value').textContent=Math.round(explode*100)+'%';$('#ghost').classList.toggle('active',!!engine?.template.ghosted);});
 on('#assemble',()=>{explode=0;selectedPart=null;if(engine){engine.template.reset();engine.isolated=false;engine.fit(engine.machine);}renderPanel();});
 on('#ghost',()=>{if(engine){engine.template.ghost(!engine.template.ghosted,selectedPart);$('#ghost').classList.toggle('active',engine.template.ghosted);}});
 on('#isolate',()=>{if(!selectedPart||!engine)return;engine.isolated=!engine.isolated;engine.template.isolate(selectedPart,engine.isolated);$('#isolate').classList.toggle('active',engine.isolated);});
 on('#tree-root',()=>{selectedTaxonomyId='O5';selectedPart=null;explode=0;engine?.template.reset();if(engine){engine.isolated=false;engine.fit(engine.machine);}renderPanel();});
 $$('[data-taxonomy]').forEach(b=>b.onclick=()=>{selectedTaxonomyId=b.dataset.taxonomy;const part=engine?.template.resolveTaxonomyNode(selectedTaxonomyId);if(part)choosePart(part);else{selectedPart=null;engine?.template.reset();}renderPanel();});
 $$('[data-stage]').forEach(b=>b.onclick=()=>{const level=+b.dataset.stage;const candidate=OFFSET5_TAXONOMY.find(n=>n.level===level&&n.meshRefs.length);if(candidate){selectedTaxonomyId=candidate.id;const part=engine?.template.resolveTaxonomyNode(candidate.id);if(part)choosePart(part);}renderPanel();});
 }else{
 const ps=photoStats();$('#panel-content').innerHTML=`<h3>Source Registry</h3><div class="card accent"><h4>${ps.unique} foto unik · ${ps.active_geometry_reference} aktif pada baseline</h4><p>${ps.supplementary_reference} supplementary · ${ps.orientation_reference} orientation · ${ps.detail_reference} detail reference.</p><span class="tag">USER EVIDENCE</span><span class="tag">GEOMETRY APPROXIMATE</span></div><h3>Foto aktual</h3>${PHOTO_REGISTRY.map(p=>`<div class="card source-photo"><h4>${esc(p.filename)}</h4><p>${esc(p.machineZone)} · ${esc(p.viewDirection)}</p><span class="tag">${esc(p.category)}</span><span class="tag">${esc(confidenceLabel(p.confidence))}</span></div>`).join('')}<h3>Sumber teknis</h3>${TECHNICAL_SOURCES.map(s=>`<div class="card"><h4>${esc(s.title)}</h4><p>${esc(s.publisher)} · ${esc(s.type)}</p><span class="tag">${esc(confidenceLabel(s.confidence))}</span><details><summary>Terminologi yang didukung</summary><p>${esc(s.supports.join(', '))}</p>${s.url?`<p><a href="${esc(s.url)}" target="_blank" rel="noopener">Buka sumber resmi/referensi ↗</a></p>`:''}</details></div>`).join('')}<div class="card"><h4>Orientasi canonical</h4><p>${esc(ORIENTATION.feedDirection)} · operator side ${esc(ORIENTATION.operatorSide)} · drive side ${esc(ORIENTATION.driveSide)}</p></div><p class="subtle">Sumber internet hanya mendukung istilah/fungsi. Geometry luar tetap mengikuti foto aktual; dimensi engineering tetap UNKNOWN.</p>`;
 }
}
function renderStatus(){
 const l=activeLayout(),engineeringScale=l?.transform?.scale;
 $('#layout-status').textContent=l?'DWG: '+l.source.file+(l.source.derivedFile?' · DXF-DERIVED':''):'DWG: BELUM TERSEDIA';
 $('#scale-status').textContent=engineeringScale?'SKALA: '+engineeringScale+' m/unit'+(l?.source?.unitStatus?.includes('CONFLICTING')?' · HEADER CONFLICT':''):'SKALA: UNKNOWN · REVIEW REQUIRED';
 $('#edit-position').disabled=role!=='admin'||!state.layout;$('#edit-position').title=role!=='admin'?'Masuk sebagai administrator untuk mengedit':!state.layout?'Kalibrasi/anchor backend diperlukan sebelum mengedit':'';
}
async function request(path,{method='GET',data,base=apiBase,key=token}={}){
 if(!base)throw new Error('URL backend Workers belum dikonfigurasi.');
 const headers={Authorization:'Bearer '+key};if(data!==undefined)headers['Content-Type']='application/json';if(method!=='GET')headers['If-Match']=String(state.revision);
 const res=await fetch(base+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(15000)});let result;try{result=await res.json();}catch{throw new Error('Respons backend bukan JSON. Periksa URL Workers.');}if(!res.ok)throw new Error(result.error||'Backend gagal merespons.');return result;
}
class CacheManager {
 async open(){return new Promise((resolve,reject)=>{const r=indexedDB.open('offset5-twin-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
 async get(key){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('data'),r=tx.objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close();});}
 async set(key,value){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);});}
 async clear(){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').clear();tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);});}
}
const cache=new CacheManager();
let cacheEnabled=false;try{cacheEnabled=localStorage.getItem('offset5-cache-enabled')==='1';}catch{}
async function acceptState(next){state=next;engine?.loadLayout(state.layout||bundledLayout);if(engine?.view==='factory')engine.setView('factory',state);renderStatus();renderPanel();if(cacheEnabled){try{await cache.set(apiBase,{state,savedAt:new Date().toISOString()});}catch{toast('Data backend dimuat; cache perangkat gagal disimpan.',true);}}}
function setView(view){const l=activeLayout();if(view==='factory'&&!l){layoutDialog();return;}editing=false;if(engine)engine.onTransform=null;explode=0;selectedPart=null;engine?.setView(view,state);$$('.rail>button').forEach(b=>b.classList.remove('active'));$('#nav-'+(view==='factory'?'layout':'machine')).classList.add('active');$('#view-kicker').textContent=view==='factory'?'LAYOUT PABRIK':'RUANG INSPEKSI';$('#view-title').textContent=view==='factory'?'Factory layout':'OFFSET 5';$('#view-subtitle').textContent=view==='factory'?l.source.file:'Heidelberg Speedmaster · CD 102-8+L';$('#lod-status').textContent=view==='factory'?'LOD 0 · DXF REFERENCE':'LOD 1 · Mesin';$('#geometry-caption').textContent=view==='factory'?'DXF-DERIVED · 0.001 m/unit · HEADER CONFLICT':'REKONSTRUKSI FOTO · APPROXIMATE · TANPA SKALA TEKNIS';$('#scene-notice').innerHTML=view==='factory'?'<span class="notice-icon">!</span><div><strong>Layout aktual berasal dari DWG/DXF pengguna</strong><span>Koordinat relatif dipertahankan. Skala 0.001 m/unit diterapkan dari anotasi metric sumber; header INSUNITS tetap CONFLICTING. OFFSET 5 belum diposisikan karena label/footprint eksplisit belum ditemukan.</span></div>':'<span class="notice-icon">!</span><div><strong>Ruang inspeksi mesin terpisah dari layout</strong><span>Geometry mesin tetap rekonstruksi foto. Plot posisi pabrik belum diterapkan sampai anchor OFFSET 5 terverifikasi.</span></div>';renderPanel();redrawPlantPlan();}
function connectionDialog(){modal('Koneksi backend',`<p>Hubungkan ruang kerja ke Cloudflare Workers untuk membaca data dan menyimpan perubahan. Token hanya berada dalam memori sesi ini.</p><form id="connection-form"><label for="api-base">URL Cloudflare Workers</label><input id="api-base" type="url" value="${esc(apiBase)}" placeholder="https://nama-worker.subdomain.workers.dev" required><label for="api-token">Token akses</label><input id="api-token" type="password" autocomplete="off" required><label class="check"><input id="enable-cache" type="checkbox" ${cacheEnabled?'checked':''}> Simpan salinan data di perangkat ini untuk akses offline</label><p class="subtle">Aktifkan hanya pada perangkat pribadi. Layout tersimpan dapat dibaca siapa pun yang memakai profil browser ini.</p><div class="actions"><button type="submit" class="primary">Hubungkan</button><button type="button" id="disconnect" class="secondary">Putuskan & hapus cache</button></div><p id="connection-error" class="inline-error" role="alert"></p></form>`);
 $('#connection-form').onsubmit=async e=>{e.preventDefault();const submit=e.target.querySelector('[type=submit]');submit.disabled=true;try{const url=new URL($('#api-base').value.trim());if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw new Error('Gunakan HTTPS untuk backend.');if(url.username||url.password||url.search||url.hash||url.pathname!=='/')throw new Error('Masukkan origin Workers tanpa path, kredensial, query, atau fragment.');const base=url.origin,key=$('#api-token').value,session=await request('/api/session',{base,key});const next=await request('/api/state',{base,key});apiBase=base;token=key;role=session.role;cacheEnabled=$('#enable-cache').checked;localStorage.setItem('offset5-api-base',base);localStorage.setItem('offset5-cache-enabled',cacheEnabled?'1':'0');if(!cacheEnabled)await cache.clear();await acceptState(next);$('#connection').textContent=role==='admin'?'Terhubung · Admin':'Terhubung · Viewer';closeModal();toast('Terhubung. Data dibaca dari backend.');}catch(err){$('#connection-error').textContent=err.message;}finally{submit.disabled=false;}};
 on('#disconnect',async()=>{token='';role=null;await cache.clear();cacheEnabled=false;localStorage.removeItem('offset5-cache-enabled');state=structuredClone(initialState);engine?.loadLayout(bundledLayout);setView(bundledLayout?'factory':'machine');renderStatus();$('#connection').textContent='Data awal · lokal';closeModal();toast('Sesi diputus dan salinan perangkat dihapus.');});
}
function layoutDialog(){const l=activeLayout(),bundled=!!bundledLayout&&!state.layout;modal('Layout pabrik · sumber DWG/DXF',`<div class="card accent"><h4>${l?'Layout sumber tersedia':'DWG/DXF belum tersedia'}</h4><p>${l?esc(l.source.file):'Tidak ada layout sumber.'}</p></div>${l?`<dl class="data-list">${pair('DWG',l.source.file)+pair('SHA-256 DWG',l.source.sha256)+pair('DXF turunan',l.source.derivedFile)+pair('Entitas modelspace',l.source.entityCount)+pair('Block',l.source.blockCount)+pair('Header unit',l.source.headerUnitsLabel)+pair('Status unit',l.source.unitStatus)+pair('Engineering scale',l.transform.scale==null?'UNKNOWN':l.transform.scale)+pair('Posisi OFFSET 5',l.positionStatus||'POSITION REVIEW REQUIRED')}</dl><div class="card"><h4>Audit plotting</h4><p>${esc(l.audit?.offset5Placement||'Anchor belum diverifikasi.')}</p><span class="tag">DXF-DERIVED</span><span class="tag">SOURCE COORDINATES PRESERVED</span></div><div class="actions"><button id="view-layout" class="primary">Buka layout</button><button id="download-layout" class="secondary">Ekspor source JSON</button><button id="mapping" class="secondary" ${role==='admin'&&state.layout?'':'disabled'}>Layer & kalibrasi</button></div>`:''}<h3>Kalibrasi / override admin</h3><p class="subtle">${bundled?'Layout bawaan adalah hasil ekstraksi DXF aktual. Skala mm→m dikalibrasi dari anotasi dan dimensi sumber; konflik header inch tetap ditampilkan. Anchor OFFSET 5 tetap memerlukan verifikasi. ':''}Impor JSON tervalidasi melalui backend hanya untuk calibration/placement yang sudah ditinjau.</p><label for="layout-file">Layout JSON tervalidasi · maksimal 4 MiB</label><input id="layout-file" type="file" accept=".json,application/json" ${role==='admin'?'':'disabled'}>${role!=='admin'?'<p class="subtle">Masuk sebagai administrator melalui Koneksi untuk mengimpor override.</p>':''}<p id="layout-error" class="inline-error" role="alert"></p>`);
 if(l){on('#view-layout',()=>{closeModal();setView('factory');});on('#download-layout',()=>download('factory-layout-source.json',l));if(state.layout&&role==='admin')on('#mapping',mappingDialog);}
 $('#layout-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>4*1024*1024)throw new Error('Batas file 4 MiB.');const layout=validateLayout(JSON.parse(await f.text()));const next=await request('/api/layout',{method:'PUT',data:layout});await acceptState(next);closeModal();setView('factory');toast('Layout override tersimpan. Tinjau kembali pemetaan terhadap sumber DXF/DWG.');}catch(err){$('#layout-error').textContent=err.message;}};
}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function mappingDialog(){const l=state.layout;if(!l||role!=='admin')return;const layers=[...new Set(l.entities.map(e=>e.layer))],semantics=['UNKNOWN','FLOOR','BOUNDARY','WALL','COLUMN','DOOR','OPENING','CORRIDOR','AREA','FOOTPRINT','LABEL','DIMENSION','STAIRS','RAMP'];modal('Layer & kalibrasi',`<p>Pemetaan tidak mengubah entitas sumber. Tinggi dinding hanya digunakan jika memiliki sumber eksplisit.</p><form id="mapping-form">${layers.map((layer,i)=>`<div class="layer-row"><span>${esc(layer)}</span><select aria-label="Semantik ${esc(layer)}" data-layer="${i}">${semantics.map(s=>`<option ${(l.layerMapping?.[layer]||'UNKNOWN')===s?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')}<h3>Transformasi koordinat</h3><p class="subtle">DWG X → Three X; DWG Y → Three Z; elevasi → Three Y.</p><label for="units">Unit sumber</label><select id="units">${['UNKNOWN','mm','cm','m','inch','foot'].map(u=>`<option ${l.transform.sourceUnits===u?'selected':''}>${u}</option>`).join('')}</select><div class="form-row"><div><label for="origin-x">Origin DWG X</label><input id="origin-x" type="number" step="any" value="${l.transform.originX}" required></div><div><label for="origin-y">Origin DWG Y</label><input id="origin-y" type="number" step="any" value="${l.transform.originY}" required></div><div><label for="map-rotation">Rotasi (°)</label><input id="map-rotation" type="number" step="any" value="${l.transform.rotation}" required></div></div><h3>Kalibrasi unit UNKNOWN (opsional)</h3><div class="form-row"><div><label for="ref-source">Jarak A–B di CAD</label><input id="ref-source" type="number" min="0.000001" step="any"></div><div><label for="ref-real">Jarak A–B sebenarnya (m)</label><input id="ref-real" type="number" min="0.000001" step="any"></div></div><label for="ref-note">Referensi titik A, B dan sumber ukuran</label><input id="ref-note"><p class="subtle">Perubahan transformasi menghapus override posisi agar tidak memakai koordinat lama pada sistem baru.</p><div class="actions"><button type="submit" class="primary">Simpan & terapkan</button></div><p id="mapping-error" class="inline-error" role="alert"></p></form>`);
 $('#mapping-form').onsubmit=async e=>{e.preventDefault();try{const next=structuredClone(l);next.layerMapping={};$$('[data-layer]').forEach(s=>next.layerMapping[layers[+s.dataset.layer]]=s.value);const u=$('#units').value,scales={mm:.001,cm:.01,m:1,inch:.0254,foot:.3048};next.transform={sourceUnits:u,originX:+$('#origin-x').value,originY:+$('#origin-y').value,rotation:+$('#map-rotation').value,scale:scales[u]??null};if(u==='UNKNOWN'&&($('#ref-source').value||$('#ref-real').value)){const sourceDistance=+$('#ref-source').value,knownDistance=+$('#ref-real').value,note=$('#ref-note').value.trim();if(!(sourceDistance>0&&knownDistance>0&&note))throw new Error('Isi kedua jarak positif serta referensinya.');next.transform.scale=knownDistance/sourceDistance;next.transform.calibration={sourceDistance,knownDistance,note};}validateLayout(next);await acceptState(await request('/api/layout',{method:'PUT',data:next}));closeModal();setView('factory');toast('Transformasi disimpan; posisi override direset.');}catch(err){$('#mapping-error').textContent=err.message;}};
}
function editorPanel(){if(role!=='admin'||!state.layout||!engine)return;setView('factory');showPanel();editing=true;engine.gizmo.setMode('translate');engine.gizmo.showX=true;engine.gizmo.showY=true;engine.gizmo.showZ=true;engine.edit(true);$('#panel-content').innerHTML=`<h3>Editor posisi</h3><div class="edit-strip">${['translate','rotate','scale'].map((m,i)=>`<button data-gizmo="${m}" class="${i?'':'active'}">${['Geser','Putar','Skala'][i]}</button>`).join('')}</div><p class="subtle">Seret gizmo pada mesin atau isi angka. Skala geometri prosedural bersifat visual; bukan dimensi mesin terverifikasi.</p><form id="position-form"><div class="form-row">${['x','y','z'].map(k=>`<div><label for="pos-${k}">Three ${k.toUpperCase()}</label><input id="pos-${k}" type="number" step="any" required></div>`).join('')}</div><div class="form-row"><div><label for="pos-rotation">Rotasi Y (°)</label><input id="pos-rotation" type="number" step="any" required></div><div><label for="pos-scale">Skala visual</label><input id="pos-scale" type="number" min="0.00001" step="any" required></div></div><label class="check"><input id="snap" type="checkbox"> Snap ke 1 unit scene</label><p class="code" id="cad-coordinates"></p><label for="position-confidence">Keyakinan posisi</label><select id="position-confidence"><option value="APPROXIMATE">APPROXIMATE</option><option value="USER-CONFIRMED">USER-CONFIRMED</option></select><div class="actions"><button type="submit" class="primary">Simpan posisi</button><button type="button" id="cancel-position" class="secondary">Batal</button><button type="button" id="reset-position" class="secondary">Reset ke sumber</button></div><p id="position-error" class="inline-error" role="alert"></p></form>`;
 const sync=()=>{for(const k of ['x','y','z'])$('#pos-'+k).value=engine.machine.position[k].toFixed(4);$('#pos-rotation').value=(engine.machine.rotation.y*180/Math.PI).toFixed(3);$('#pos-scale').value=engine.machine.scale.x.toFixed(4);const cad=worldToCad(engine.machine.position.x,engine.machine.position.z,state.layout.transform);$('#cad-coordinates').textContent=`DWG X: ${number(cad.x)}\nDWG Y: ${number(cad.y)}\nUnit: ${state.layout.transform.sourceUnits}`;};engine.onTransform=sync;sync();
 $$('[data-gizmo]').forEach(b=>b.onclick=()=>{engine.gizmo.setMode(b.dataset.gizmo);engine.gizmo.showX=b.dataset.gizmo!=='rotate';engine.gizmo.showY=b.dataset.gizmo!=='scale';engine.gizmo.showZ=b.dataset.gizmo==='translate';$$('[data-gizmo]').forEach(c=>c.classList.toggle('active',b===c));});$('#snap').onchange=e=>{engine.gizmo.setTranslationSnap(e.target.checked?1:null);engine.gizmo.setRotationSnap(e.target.checked?Math.PI/12:null);engine.gizmo.setScaleSnap(e.target.checked?.1:null);};
 $$('[id^="pos-"]').forEach(el=>el.onchange=()=>{const vals=['x','y','z','rotation','scale'].map(k=>+$('#pos-'+k).value);if(vals.every(Number.isFinite)&&vals[4]>0){engine.machine.position.set(...vals.slice(0,3));engine.machine.rotation.set(0,vals[3]*Math.PI/180,0);engine.machine.scale.setScalar(vals[4]);sync();}});
 const end=()=>{engine.edit(false);engine.onTransform=null;editing=false;engine.applyPlacement(state);renderPanel();};on('#cancel-position',end);on('#reset-position',async()=>{await acceptState(await request('/api/position',{method:'DELETE'}));end();toast('Override dihapus. Posisi kembali mengikuti sumber DWG jika tersedia.');});
 $('#position-form').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(['x','y','z','rotation','scale'].map(k=>[k,+$('#pos-'+k).value]));p.confidence=$('#position-confidence').value;validatePosition(p);await acceptState(await request('/api/position',{method:'PUT',data:p}));end();toast('Posisi tersimpan di backend.');}catch(err){$('#position-error').textContent=err.message;}};
}
function assetDialog(){modal('Aset pabrik',`<label for="asset-search">Cari nama, kode, model, atau manufacturer</label><input id="asset-search" type="search" placeholder="Cari OFFSET 5…"><div id="asset-results"></div><p class="subtle" style="margin-top:18px">1 aset mesin dikembangkan. Aset lain baru muncul sebagai footprint ketika dapat diidentifikasi di DWG.</p>`);const render=()=>{const q=$('#asset-search').value.toLowerCase();const found=['description','asset_code','model','manufacturer','category'].some(k=>String(state.asset[k]).toLowerCase().includes(q));$('#asset-results').innerHTML=found?'<button id="asset-result" class="list-button"><span class="asset-icon">05</span><span><strong>OFFSET 5</strong><small>Heidelberg · CD 102-8+L</small></span></button>':'<p class="empty">Tidak ada aset yang sesuai.</p>';if(found)on('#asset-result',()=>{closeModal();setView('machine');showPanel();});};$('#asset-search').oninput=render;render();}
function settingsDialog(){modal('Pengaturan tampilan',`<label class="check"><input id="low-mode" type="checkbox" ${engine?.low?'checked':''}> Mode ringan · kurangi bayangan dan resolusi</label><label class="check"><input id="label-mode" type="checkbox" ${engine?.labels?'checked':''}> Label aset</label><h3>Data perangkat</h3><p>Cache offline ${cacheEnabled?'aktif':'tidak aktif'}. Pengaturan visual disimpan di perangkat ini; perubahan data harus disimpan melalui backend.</p><button id="clear-cache" class="secondary">Hapus salinan offline</button>`);$('#low-mode').onchange=e=>{engine?.setLow(e.target.checked);localStorage.setItem('offset5-low',e.target.checked?'1':'0');};$('#label-mode').onchange=e=>{if(engine)engine.labels=e.target.checked;$('#labels').classList.toggle('active',e.target.checked);};on('#clear-cache',async()=>{await cache.clear();toast('Salinan offline dihapus.');});}
function helpDialog(){modal('Panduan ruang kerja',`<h3>Navigasi 3D</h3><p>Geser dengan satu jari atau tombol kiri mouse untuk memutar. Cubit atau scroll untuk zoom. Dua jari atau tombol kanan untuk menggeser. Tombol Atas, Isometrik, Fokus, dan Reset menyediakan navigasi alternatif.</p><h3>Inspeksi dan struktur</h3><p>Klik mesin untuk membuka detail. Tab Struktur menampilkan kelompok bentuk luar dari foto. Pilih bagian, lalu gerakkan slider untuk memisahkan hanya pilihan. Rakit kembali atau klik ganda pada scene mengembalikan susunannya.</p><h3>Ketepatan data</h3><p>RECONSTRUCTED / APPROXIMATE berarti bentuk direkonstruksi dari foto dengan proporsi perkiraan. UNKNOWN berarti data belum tersedia. Susunan delapan housing visual bukan verifikasi jumlah unit atau komponen internal.</p><h3>Layout pabrik</h3><p>DWG asli harus diekstrak dan ditinjau. Tidak ada denah contoh. Entitas yang belum dapat dirender tetap disimpan sebagai sumber.</p><h3>Penyimpanan</h3><p>Viewer hanya membaca. Administrator dapat mengimpor layout dan mengubah posisi. Cache offline bersifat opsional dan bukan sinkronisasi perubahan.</p>`);}

renderPanel();renderStatus();if(matchMedia('(max-width:800px)').matches)document.body.classList.add('panel-hidden');
try{engine=new FactoryEngine($('#viewport'),part=>{choosePart(part);showPanel();renderPanel('structure');});engine.onReset=()=>{explode=0;selectedPart=null;renderPanel();};engine.onError=message=>toast(message,true);$('#boot').hidden=true;$('#engine-status').textContent='WebGL 2 · Siap';try{engine.setLow(localStorage.getItem('offset5-low')==='1');}catch{}}catch(e){$('#boot').innerHTML='<strong>WebGL 2 tidak tersedia</strong><p>Coba browser yang mendukung akselerasi grafis. Metadata dan sumber tetap dapat dibaca.</p>';$('#engine-status').textContent='3D tidak tersedia';toast('Penampil 3D gagal: '+e.message,true);}
try{bundledLayout=await loadBundledPlantLayout();if(!state.layout)engine?.loadLayout(bundledLayout);renderStatus();redrawPlantPlan();if(engine)setView('machine');}catch(e){toast('Layout DXF bawaan gagal dimuat: '+e.message,true);}
$$('[data-tab]').forEach(b=>b.onclick=()=>{if(editing){engine.edit(false);engine.applyPlacement(state);engine.onTransform=null;editing=false;}renderPanel(b.dataset.tab);});
on('#modal-close',closeModal);on('#connect',connectionDialog);on('#nav-machine',()=>setView('machine'));on('#nav-layout',layoutDialog);on('#notice-details',layoutDialog);on('#nav-assets',assetDialog);on('#nav-sources',()=>{showPanel();renderPanel('sources');});on('#nav-help',helpDialog);on('#settings',settingsDialog);on('#panel-toggle',()=>document.body.classList.toggle('panel-hidden'));on('#close-panel',()=>document.body.classList.add('panel-hidden'));on('#focus-machine',()=>{if(!engine?.machine.visible)setView('machine');engine?.fit(engine.machine);});on('#edit-position',editorPanel);
$$('[data-camera]').forEach(b=>b.onclick=()=>{if(!engine)return;const mode=b.dataset.camera;$$('[data-camera]').forEach(c=>c.classList.toggle('active',c===b));const target=engine.view==='factory'?engine.factory:engine.machine;if(mode==='reset'){explode=0;selectedPart=null;engine.isolated=false;engine.template.reset();renderPanel();engine.fit(target,'iso');}else engine.fit(target,mode==='top'?'top':'iso');});
on('#tool-pan',()=>{if(!engine)return;engine.controls.enablePan=!engine.controls.enablePan;$('#tool-pan').classList.toggle('active',engine.controls.enablePan);toast(engine.controls.enablePan?'Mode pan aktif · gunakan dua jari / klik kanan':'Mode pan nonaktif');});
on('#tool-explode',()=>{showPanel();selectedTaxonomyId=selectedTaxonomyId||'O5';renderPanel('structure');explode=explode>.01?0:.65;engine?.template.explode(explode,selectedPart);renderPanel('structure');});
on('#tool-isolate',()=>{if(!engine||!selectedPart){showPanel();renderPanel('structure');toast('Pilih node taxonomy yang terhubung ke 3D terlebih dahulu.',true);return;}engine.isolated=!engine.isolated;engine.template.isolate(selectedPart,engine.isolated);$('#tool-isolate').classList.toggle('active',engine.isolated);});
on('#labels',()=>{if(engine){engine.labels=!engine.labels;$('#labels').classList.toggle('active',engine.labels);}});on('#fullscreen',async()=>{if(!document.fullscreenEnabled){toast('Layar penuh tidak didukung browser ini.');return;}if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();});
window.addEventListener('offline',()=>{$('#connection').textContent='OFFLINE · Data di memori';toast('Koneksi terputus. Perubahan belum dapat disimpan.');});window.addEventListener('online',()=>{$('#connection').textContent=role?'Koneksi pulih · Muat ulang data':'Data awal · lokal';if(role)request('/api/state').then(acceptState).then(()=>{$('#connection').textContent='Terhubung · '+role;toast('Data backend dimuat ulang.');}).catch(e=>toast(e.message,true));});
try{const config=await fetch('./config.json').then(r=>r.json());apiBase=localStorage.getItem('offset5-api-base')||config.apiBase||'';if(cacheEnabled&&apiBase){const cached=await cache.get(apiBase);if(cached?.state){state=cached.state;engine?.loadLayout(state.layout||bundledLayout);renderStatus();renderPanel();$('#connection').textContent='CACHED DATA · '+new Date(cached.savedAt).toLocaleDateString('id-ID');}}}catch(e){toast('Konfigurasi atau cache tidak dapat dibaca. Data awal tetap tersedia.',true);}
window.addEventListener('resize',redrawPlantPlan,{passive:true});$('#ui-workbench-toggle')?.addEventListener('click',()=>setTimeout(redrawPlantPlan,80));$('[data-workbench="dwg"]').forEach(b=>b.addEventListener('click',()=>setTimeout(redrawPlantPlan,40)));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
window.addEventListener('pagehide',()=>{token='';});
