import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';

export const PHOTO_RECONSTRUCTION={
  version:'offset5-photo-v4',status:'RECONSTRUCTED / APPROXIMATE',dimensionUnit:'VISUAL_ONLY',
  installedConfiguration:'CD 102-8+L UV identity visible in user photo; exact optional equipment remains reviewable',
  photoCount:16,
  orientation:{feedDirection:'+X',feederEnd:'-X',deliveryEnd:'+X',operatorSide:'+Z',oppositeSide:'-Z'},
  photos:['IMG_2312.jpeg','IMG_1970.jpeg','IMG_1971.jpeg','IMG_1656.jpeg','IMG_1624.jpeg','IMG_1625.jpeg','IMG_1626.jpeg','IMG_1627.jpeg','IMG_1628.jpeg','IMG_1629.jpeg','IMG_1630.jpeg','IMG_1631.jpeg','IMG_1633.jpeg','IMG_1634.jpeg','IMG_1165.jpeg','IMG_0947.jpeg']
};

const V=a=>new THREE.Vector3(...a);
const TAXONOMY=['MESIN','UNIT UTAMA','SUB','BLOCK','PART','SPESIFIK PART'];

export class OffsetMachineTemplate{
  constructor(){
    this.root=new THREE.Group();this.root.name='OFFSET 5 · Heidelberg Speedmaster CD 102-8+L UV';
    this.root.userData={assetId:'MACHINE-OFFSET5',nodeId:'offset5',selectable:false,taxonomyLevel:1,taxonomyLabel:TAXONOMY[0],...PHOTO_RECONSTRUCTION};
    this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.ghosted=false;
    this.palette={graphite:0x30383d,black:0x151b20,silver:0xaeb8b8,steel:0x889598,light:0xd1d4c9,paper:0xeee9d5,rubber:0x20252a,glass:0x23333a,red:0xb33c32,blue:0x243e70,dial:0xe9e2c4};
    this.build();this.batchMeshes();
    for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}
    this.root.updateMatrixWorld(true);
  }
  group(parent,id,name,level,pos=[0,0,0],explode=[0,0,0],sources=[],note='',confidence='PHOTO_VERIFIED'){
    const g=new THREE.Group();g.name=name;g.position.set(...pos);
    g.userData={assetId:'MACHINE-OFFSET5',nodeId:id,selectable:true,taxonomyLevel:level,taxonomyLabel:TAXONOMY[level-1],visualOnly:true,confidence,source:'USER_PHOTOS + RESEARCH',sourceFiles:sources,note,explode:V(explode)};
    parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;
  }
  material(kind,owner){const key=(owner.userData.nodeId||'root')+':'+kind;if(!this.materials.has(key))this.materials.set(key,new THREE.MeshStandardMaterial({color:this.palette[kind]??this.palette.graphite,metalness:['silver','steel'].includes(kind)?.62:kind==='paper'||kind==='dial'?0:.24,roughness:kind==='paper'?.9:kind==='glass'?.18:kind==='dial'?.72:.46,transparent:kind==='glass',opacity:kind==='glass'?.64:1}));return this.materials.get(key);}
  mesh(parent,geo,key,kind,pos,rot){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.material(kind,parent));m.position.set(...pos);if(rot)m.rotation.set(...rot);m.castShadow=kind!=='glass';m.receiveShadow=true;m.userData={assetId:'MACHINE-OFFSET5',ownerId:parent.userData.nodeId};parent.add(m);this.meshes.push(m);return m;}
  box(g,size,pos,kind='graphite',radius=0,rot=null){return this.mesh(g,()=>radius?new RoundedBoxGeometry(...size,2,radius):new THREE.BoxGeometry(...size),'box:'+size+':'+radius,kind,pos,rot);}
  cylinder(g,r,len,pos,kind='steel',axis='z'){return this.mesh(g,()=>new THREE.CylinderGeometry(r,r,len,18),'cyl:'+r+':'+len,kind,pos,axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:[0,0,0]);}
  tube(g,pts,r=.024,kind='rubber'){const c=new THREE.CatmullRomCurve3(pts.map(V));return this.mesh(g,()=>new THREE.TubeGeometry(c,24,r,7,false),'tube:'+JSON.stringify(pts)+':'+r,kind,[0,0,0]);}
  gauge(g,pos){this.cylinder(g,.07,.028,pos,'black','z');this.cylinder(g,.056,.012,[pos[0],pos[1],pos[2]+.018],'dial','z');}
  grille(g,pos,w,h,axis='x'){const [x,y,z]=pos;if(axis==='x'){this.box(g,[.035,h,w],[x,y,z],'black');for(let i=0;i<13;i++)this.box(g,[.05,.014,w],[x+.025,y-h/2+i*h/12,z],'steel');for(let i=0;i<9;i++)this.box(g,[.05,h,.012],[x+.028,y,z-w/2+i*w/8],'graphite');}else{this.box(g,[w,h,.035],[x,y,z],'black');for(let i=0;i<10;i++)this.box(g,[w,.014,.05],[x,y-h/2+i*h/9,z+.025],'steel');for(let i=0;i<10;i++)this.box(g,[.012,h,.05],[x-w/2+i*w/9,y,z+.028],'graphite');}}
  tread(g,size,pos){this.box(g,size,pos,'steel',.035);const key='tread-rib';if(!this.geometries.has(key))this.geometries.set(key,new THREE.BoxGeometry(.065,.008,.017));const nx=Math.max(1,Math.floor(size[0]/.14)),nz=Math.max(1,Math.floor(size[2]/.14));const m=new THREE.InstancedMesh(this.geometries.get(key),this.material('silver',g),nx*nz),d=new THREE.Object3D();let k=0;for(let i=0;i<nx;i++)for(let j=0;j<nz;j++){d.position.set(pos[0]-size[0]/2+(i+.5)*size[0]/nx,pos[1]+size[1]/2+.004,pos[2]-size[2]/2+(j+.5)*size[2]/nz);d.rotation.y=(i+j)%2?Math.PI/4:-Math.PI/4;d.updateMatrix();m.setMatrixAt(k++,d.matrix);}m.userData={assetId:'MACHINE-OFFSET5',ownerId:g.userData.nodeId,detail:true};m.receiveShadow=true;g.add(m);this.meshes.push(m);}
  batchMeshes(){for(const g of this.nodes){const b=new Map();for(const m of g.children.filter(c=>c.isMesh&&!c.isInstancedMesh)){if(!b.has(m.material))b.set(m.material,[]);b.get(m.material).push(m);}for(const [mat,meshes] of b){if(meshes.length<2)continue;const pieces=meshes.map(m=>{m.updateMatrix();return (m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone()).applyMatrix4(m.matrix);});const merged=mergeGeometries(pieces);pieces.forEach(x=>x.dispose());if(!merged)continue;this.geometries.set('merged:'+g.userData.nodeId+':'+mat.uuid,merged);const out=new THREE.Mesh(merged,mat);out.castShadow=true;out.receiveShadow=true;out.userData={assetId:'MACHINE-OFFSET5',ownerId:g.userData.nodeId};for(const old of meshes){g.remove(old);this.meshes.splice(this.meshes.indexOf(old),1);}g.add(out);this.meshes.push(out);}}}

  build(){this.feeder(-8.55);this.printingGroup(-6.55);this.coatingUnit(3.25);this.deliveryTransfer(5.05);this.inspectionSystem(6.55);this.deliveryPile(8.15);this.platform();this.controlConsole(-8.25,0,-3.15);this.auxiliary();}

  feeder(x){
    const u=this.group(this.root,'feeder','Feeder / Anleger',2,[x,0,0],[-1.7,0,0],['IMG_2312.jpeg','IMG_1634.jpeg'],'Ujung pile dengan fascia putih dan pagar vertikal pada IMG_2312 dipakai sebagai feeder. Ini membalik assignment v3 yang sebelumnya tertukar.');
    const pile=this.group(u,'feeder-pile-system','Pile inlet system',3,[0,0,0],[-.45,0,0],['IMG_2312.jpeg']);const frame=this.group(pile,'feeder-pile-frame','Pile frame',4,[0,0,0],[-.3,.15,0],['IMG_2312.jpeg']);const table=this.group(frame,'feeder-pile-table','Pile table',5,[0,0,0],[0,-.35,0],['IMG_2312.jpeg']);const stack=this.group(table,'feeder-paper-stack','Visible paper pile',6,[0,0,0],[0,-.25,0],['IMG_2312.jpeg'],'Isi visual; tinggi pile bukan data produksi.');this.box(stack,[1.08,.82,1.7],[0,.73,0],'paper',.01);this.box(table,[1.18,.10,1.82],[0,.25,0],'steel');
    const guard=this.group(frame,'feeder-front-guard','Front pile guard',5,[0,0,0],[.35,0,0],['IMG_2312.jpeg']);const bars=this.group(guard,'feeder-guard-bars','Vertical guard bars',6,[0,0,0],[.3,0,0],['IMG_2312.jpeg']);for(let i=0;i<13;i++)this.cylinder(bars,.014,1.25,[.72,.92,-.9+i*.15],'steel','y');
    const fascia=this.group(u,'feeder-upper-housing','Upper feeder housing',3,[0,0,0],[0,.55,0],['IMG_2312.jpeg','IMG_1634.jpeg']);const shell=this.group(fascia,'feeder-fascia-block','White fascia and inspection window',4,[0,0,0],[0,.35,0],['IMG_2312.jpeg']);const upper=this.group(shell,'feeder-upper-panel','Upper fascia panel',5,[0,0,0],[0,.25,0],['IMG_2312.jpeg']);this.box(upper,[1.85,.25,2.28],[0,2.43,0],'light',.025);const window=this.group(shell,'feeder-window','Dark inspection window',5,[0,0,0],[.25,0,0],['IMG_2312.jpeg']);const glass=this.group(window,'feeder-window-glass','Inspection glass',6,[0,0,0],[.2,0,0],['IMG_2312.jpeg']);this.box(glass,[.05,.58,1.35],[.93,1.95,0],'glass',.015);
    const controls=this.group(fascia,'feeder-controls','Local feeder controls',4,[0,0,0],[0,.25,1.0],['IMG_2312.jpeg']);const buttons=this.group(controls,'feeder-control-buttons','Visible control buttons',5,[0,0,0],[0,.2,0],['IMG_2312.jpeg']);const eStop=this.group(buttons,'feeder-estop','Emergency-stop / local button cluster',6,[0,0,0],[0,.2,0],['IMG_2312.jpeg'],'Visual placement only; electrical function not inferred.');for(let i=0;i<5;i++)this.cylinder(eStop,.025,.024,[.78,2.35-i*.11,1.08],i===0?'red':'black','x');
    const board=this.group(u,'feeder-feed-board','Feed board / transfer-in',3,[1.15,0,0],[.45,.2,0],['IMG_2312.jpeg']);const boardBlock=this.group(board,'feeder-board-block','Feed board block',4,[0,0,0],[.35,.15,0],['IMG_2312.jpeg']);const boardPart=this.group(boardBlock,'feeder-board-surface','Feed board surface',5,[0,0,0],[.25,.1,0],['IMG_2312.jpeg']);const boardTop=this.group(boardPart,'feeder-board-top','Visible board top',6,[0,0,0],[.2,.1,0],['IMG_2312.jpeg']);this.box(boardTop,[1.05,.09,1.92],[0,.93,0],'steel',.02);
  }

  printingGroup(x0){const u=this.group(this.root,'printing-units','Printing Units Group · PU1–PU8',2,[0,0,0],[0,.35,0],['IMG_1627.jpeg','IMG_1628.jpeg','IMG_2312.jpeg'],'Urutan delapan unit mengikuti identitas CD 102-8+L dan kontinuitas foto; internal tersembunyi tidak dimodelkan sebagai fakta terpasang.');for(let i=0;i<8;i++)this.printUnit(u,i+1,x0+i*1.22);}
  printUnit(parent,n,x){
    const src=['IMG_1627.jpeg','IMG_1628.jpeg'];const s=this.group(parent,'pu'+n,'Printing Unit '+n,3,[x,0,0],[(n-4.5)*.18,.16,0],src);
    const housing=this.group(s,'pu'+n+'-housing','External housing',4,[0,0,0],[0,.15,1.0],src);const op=this.group(housing,'pu'+n+'-operator-cover','Operator-side curved cover',5,[0,0,0],[0,.12,1.0],src);const opPanel=this.group(op,'pu'+n+'-operator-panel','Curved side panel',6,[0,0,0],[0,.12,.8],src);this.box(opPanel,[.88,1.88,.28],[0,1.38,1.05],'silver',.12);
    const drive=this.group(housing,'pu'+n+'-opposite-cover','Opposite-side cover / grille',5,[0,0,0],[0,.12,-1.0],['IMG_0947.jpeg','IMG_1628.jpeg'],'Opposite side visualized from visible grilles; drive-side designation not asserted.');const grille=this.group(drive,'pu'+n+'-guard-grille','Protective grille',6,[0,0,0],[0,.1,-.7],['IMG_0947.jpeg','IMG_1628.jpeg']);this.grille(grille,[.47,1.72,0],1.72,.78,'x');
    const ink=this.group(s,'pu'+n+'-ink-dampening','Inking / dampening visible zone',4,[0,0,0],[0,.7,0],['IMG_1970.jpeg','IMG_1971.jpeg','IMG_1628.jpeg'],'Taxonomy follows Heidelberg press architecture; only visible upper roller/fountain geometry is rendered.');const fountain=this.group(ink,'pu'+n+'-ink-fountain','Ink fountain / upper trough',5,[0,0,0],[0,.45,0],['IMG_1970.jpeg','IMG_1971.jpeg']);const roller=this.group(fountain,'pu'+n+'-upper-roller','Visible upper roller',6,[0,0,0],[0,.35,0],['IMG_1970.jpeg','IMG_1971.jpeg']);this.cylinder(roller,.105,1.6,[-.05,2.47,0],n===1?'red':n===2?'blue':'rubber');this.box(fountain,[.42,.08,1.68],[-.08,2.36,0],'steel',.025);
    const cylinderZone=this.group(s,'pu'+n+'-cylinder-zone','Cylinder zone',4,[0,0,0],[0,-.15,-.45],src,'CD 102 platform uses large-diameter cylinder architecture in official Heidelberg material; exact installed internal geometry is not exposed here.','REFERENCE_ONLY');const guard=this.group(cylinderZone,'pu'+n+'-cylinder-guard','Cylinder guard',5,[0,0,0],[0,-.1,-.4],src);const visible=this.group(guard,'pu'+n+'-visible-cylinder-guard','Visible guard surface',6,[0,0,0],[0,-.1,-.3],src);this.box(visible,[1.02,.58,1.9],[0,.74,0],'graphite',.04);
    const access=this.group(s,'pu'+n+'-access','Access & step',4,[0,0,0],[0,-.2,1.2],src);const step=this.group(access,'pu'+n+'-step','Operator step',5,[0,0,0],[0,-.2,1.0],src);const tread=this.group(step,'pu'+n+'-step-tread','Step tread plate',6,[0,0,0],[0,-.18,.8],src);this.tread(tread,[.47,.10,.52],[.48,.77,1.42]);
  }

  coatingUnit(x){
    const u=this.group(this.root,'coating-unit','Coating Unit · L',2,[x,0,0],[.65,.25,0],['IMG_1165.jpeg','IMG_0947.jpeg','IMG_1631.jpeg'],'Unit L wajib berada setelah PU8 dan sebelum delivery berdasarkan CD 102-8+L. Detail roller-service dari IMG_1165/0947 ditempatkan di sini sebagai posisi inferensi, bukan ukuran teknik.','INFERRED_POSITION');const body=this.group(u,'coating-body','Coating housing',3,[0,0,0],[.3,.2,0],['IMG_1631.jpeg','IMG_1629.jpeg']);const housing=this.group(body,'coating-housing-block','Main housing block',4,[0,0,0],[.25,.15,0],['IMG_1631.jpeg']);const cover=this.group(housing,'coating-side-cover','Side cover',5,[0,0,0],[.2,.1,1.0],['IMG_1631.jpeg']);const panel=this.group(cover,'coating-cover-panel','Visible cover panel',6,[0,0,0],[.15,.1,.8],['IMG_1631.jpeg']);this.box(panel,[1.25,1.62,2.05],[0,1.2,0],'graphite',.05);
    const rollerZone=this.group(u,'coating-roller-zone','Roller / service zone',3,[0,0,0],[.25,.45,-.6],['IMG_1165.jpeg','IMG_0947.jpeg'],'Visible roller/gauge details assigned to coating-service zone by line order; exact sub-function remains reviewable.','INFERRED_POSITION');const guard=this.group(rollerZone,'coating-roller-guard','Roller guard block',4,[0,0,0],[.2,.2,-.5],['IMG_0947.jpeg']);const rollerPart=this.group(guard,'coating-visible-rollers','Visible roller set',5,[0,0,0],[.15,.15,-.35],['IMG_0947.jpeg']);const segmented=this.group(rollerPart,'coating-segmented-roller','Segmented roller',6,[0,0,0],[.1,.1,-.3],['IMG_0947.jpeg']);this.cylinder(segmented,.10,1.82,[-.18,1.08,0],'steel');for(let i=0;i<10;i++)this.cylinder(segmented,.108,.09,[-.18,1.08,-.78+i*.173],'rubber');
    const service=this.group(rollerZone,'coating-service-panel','Service panel',4,[0,0,0],[.25,.2,.65],['IMG_1165.jpeg']);const gauges=this.group(service,'coating-gauge-panel','Three-gauge panel',5,[0,0,0],[.2,.15,.5],['IMG_1165.jpeg']);for(let i=0;i<3;i++){const q=this.group(gauges,'coating-gauge-'+(i+1),'Gauge '+(i+1),6,[0,0,0],[.1,.1,0],['IMG_1165.jpeg']);this.gauge(q,[.32+i*.15,1.15,1.04]);}const hose=this.group(service,'coating-service-hose','Corrugated service hose',5,[0,0,0],[.15,.15,.4],['IMG_1165.jpeg']);const hoseLeaf=this.group(hose,'coating-hose-line','Visible hose line',6,[0,0,0],[.1,.1,.3],['IMG_1165.jpeg']);this.tube(hoseLeaf,[[.04,1.2,.82],[-.06,.98,.94],[-.06,.72,.91],[.1,.57,.84]],.055,'rubber');
  }

  deliveryTransfer(x){const u=this.group(this.root,'delivery','Delivery / Ausleger',2,[0,0,0],[1.6,0,0],['IMG_1624.jpeg','IMG_1629.jpeg','IMG_1631.jpeg','IMG_1633.jpeg'],'Delivery adalah ujung +X. Assignment v3 yang memakai IMG_2312 sebagai delivery telah dikoreksi.');const transfer=this.group(u,'delivery-transfer','Delivery transfer section',3,[x,0,0],[.55,.15,0],['IMG_1629.jpeg','IMG_1631.jpeg','IMG_1633.jpeg']);const deck=this.group(transfer,'delivery-transfer-deck','Transfer deck',4,[0,0,0],[.4,.12,0],['IMG_1633.jpeg']);const deckPart=this.group(deck,'delivery-deck-surface','Deck surface',5,[0,0,0],[.3,.1,0],['IMG_1633.jpeg']);const deckLeaf=this.group(deckPart,'delivery-deck-tread','Tread surface',6,[0,0,0],[.2,.08,0],['IMG_1633.jpeg']);this.tread(deckLeaf,[3.1,.10,2.08],[0,.95,0]);const hood=this.group(transfer,'delivery-hood-block','Sloped hood block',4,[0,0,0],[0,.7,-.35],['IMG_1629.jpeg','IMG_1631.jpeg']);const hoodPart=this.group(hood,'delivery-sloped-cover','Sloped cover',5,[0,0,0],[0,.5,-.3],['IMG_1629.jpeg','IMG_1631.jpeg']);const left=this.group(hoodPart,'delivery-sloped-cover-main','Main sloped panel',6,[0,0,0],[0,.4,-.2],['IMG_1629.jpeg','IMG_1631.jpeg']);this.box(left,[2.15,.12,2.02],[-.25,1.62,0],'graphite',.025,[0,0,-.34]);this._deliveryRoot=u;}

  inspectionSystem(x){
    const u=this.group(this.root,'inspection-system','Inline Inspection System · FA-Swan / Focusight powered by AVT',2,[x,0,0],[.8,.7,0],['IMG_1630.jpeg','IMG_1633.jpeg'],'Branding is directly visible on user photos. Focusight sources describe FA-SWAN as an offset-printing online inspection system; exact installed camera/light specification remains unverified.');const bridge=this.group(u,'inspection-bridge','Inspection bridge frame',3,[0,0,0],[0,.45,0],['IMG_1630.jpeg','IMG_1633.jpeg']);const supports=this.group(bridge,'inspection-support-block','Support block',4,[0,0,0],[0,.35,0],['IMG_1630.jpeg']);for(const z of [-1.13,1.13]){const leg=this.group(supports,'inspection-leg-'+(z>0?'operator':'opposite'),z>0?'Operator-side support leg':'Opposite support leg',5,[0,0,0],[0,.25,z>0?.35:-.35],['IMG_1630.jpeg']);const leaf=this.group(leg,'inspection-leg-'+(z>0?'operator':'opposite')+'-column','Support column',6,[0,0,0],[0,.2,z>0?.3:-.3],['IMG_1630.jpeg']);this.box(leaf,[.20,2.35,.24],[0,1.46,z],'light',.035);}const beam=this.group(bridge,'inspection-top-beam','Top beam',4,[0,0,0],[0,.35,0],['IMG_1630.jpeg','IMG_1633.jpeg']);const beamPart=this.group(beam,'inspection-beam-housing','Beam housing',5,[0,0,0],[0,.25,0],['IMG_1630.jpeg']);const beamLeaf=this.group(beamPart,'inspection-beam-visible','FA-Swan visible beam',6,[0,0,0],[0,.2,0],['IMG_1630.jpeg']);this.box(beamLeaf,[.20,.23,2.52],[0,2.68,0],'graphite',.03);
    const imaging=this.group(u,'inspection-imaging','Visual imaging assembly',3,[0,0,0],[0,.65,0],['IMG_1630.jpeg','IMG_1633.jpeg'],'Official Focusight taxonomy: visual imaging system includes cooled lighting and dual camera options; installed internals are not assumed.','REFERENCE_PLUS_PHOTO');const pods=this.group(imaging,'inspection-pods-block','Visible imaging pod block',4,[0,0,0],[0,.45,0],['IMG_1630.jpeg']);for(let i=0;i<4;i++){const z=-.72+i*.48;const pod=this.group(pods,'inspection-pod-'+(i+1),'Visible pod '+(i+1),5,[0,0,0],[0,.3,z<0?-.25:.25],['IMG_1630.jpeg']);const podLeaf=this.group(pod,'inspection-pod-'+(i+1)+'-housing','Pod housing',6,[0,0,0],[0,.2,z<0?-.2:.2],['IMG_1630.jpeg']);this.box(podLeaf,[.34,.30,.24],[.04,2.43,z],'graphite',.035,[0,0,z<0?-.10:.10]);this.cylinder(podLeaf,.075,.03,[.205,2.35,z],'black','x');}
  }

  deliveryPile(x){const u=this._deliveryRoot;const pile=this.group(u,'delivery-pile','Delivery pile section',3,[x,0,0],[.75,0,0],['IMG_1624.jpeg','IMG_1625.jpeg']);const frame=this.group(pile,'delivery-pile-frame','Open delivery pile frame',4,[0,0,0],[.5,.15,0],['IMG_1624.jpeg']);const columns=this.group(frame,'delivery-frame-columns','Delivery frame columns',5,[0,0,0],[.4,.1,0],['IMG_1624.jpeg']);const columnsLeaf=this.group(columns,'delivery-frame-visible','Visible open frame',6,[0,0,0],[.3,.1,0],['IMG_1624.jpeg']);for(const z of [-1.02,1.02])for(const a of [-.67,.67])this.box(columnsLeaf,[.20,2.48,.23],[a,1.29,z],'graphite',.025);this.box(columnsLeaf,[1.64,.38,2.32],[0,2.62,0],'graphite',.05);const pileTable=this.group(frame,'delivery-pile-table','Delivery pile table',5,[0,0,0],[.35,-.2,0],['IMG_1624.jpeg','IMG_1625.jpeg']);const sheetPile=this.group(pileTable,'delivery-sheet-pile','Visible output pile',6,[0,0,0],[.25,-.18,0],['IMG_1624.jpeg','IMG_1625.jpeg']);this.box(sheetPile,[1.08,.85,1.55],[0,.68,0],'paper',.008);this.box(pileTable,[1.18,.11,1.68],[0,.20,0],'steel');}

  platform(){const u=this.group(this.root,'operator-platform','Operator Platform & Walkway',2,[0,0,0],[0,-.35,1.3],['IMG_1627.jpeg','IMG_1628.jpeg','IMG_1629.jpeg','IMG_1631.jpeg','IMG_1633.jpeg']);const walk=this.group(u,'platform-main','Main operator-side walkway',3,[0,0,0],[0,-.25,1.0],['IMG_1629.jpeg','IMG_1633.jpeg']);const structure=this.group(walk,'platform-structure','Walkway support block',4,[0,0,0],[0,-.2,.8],['IMG_1629.jpeg']);const deck=this.group(structure,'platform-deck','Walkway deck',5,[0,0,0],[0,-.15,.7],['IMG_1629.jpeg']);const tread=this.group(deck,'platform-tread','Diamond tread surface',6,[0,0,0],[0,-.1,.6],['IMG_1629.jpeg']);this.tread(tread,[17.6,.14,1.05],[.2,.20,1.57]);const steps=this.group(u,'platform-steps','Unit access steps',3,[0,0,0],[0,-.25,1.35],['IMG_1627.jpeg','IMG_1628.jpeg']);for(let i=0;i<9;i++){const st=this.group(steps,'platform-step-'+(i+1),'Access step '+(i+1),4,[0,0,0],[0,-.15,1.0],['IMG_1627.jpeg']);const p=this.group(st,'platform-step-'+(i+1)+'-plate','Step plate',5,[0,0,0],[0,-.1,.8],['IMG_1627.jpeg']);const l=this.group(p,'platform-step-'+(i+1)+'-tread','Step tread',6,[0,0,0],[0,-.08,.7],['IMG_1627.jpeg']);this.tread(l,[.5,.10,.52],[-5.75+i*1.22,.68,1.45]);}}

  controlConsole(x,y,z){const u=this.group(this.root,'control-console','Console & External Support',2,[x,y,z],[-.5,0,-1.1],['IMG_1634.jpeg','IMG_1656.jpeg'],'Console is spatially separate from main press body in the user photos; dimensions are visual only.');const s=this.group(u,'console-main','Main control console',3,[0,0,0],[0,.2,-.6],['IMG_1634.jpeg']);const b=this.group(s,'console-desk-block','Console desk block',4,[0,0,0],[0,.15,-.4],['IMG_1634.jpeg']);const p=this.group(b,'console-desk','Desk and cabinet',5,[0,0,0],[0,.1,-.3],['IMG_1634.jpeg']);const leaf=this.group(p,'console-desk-visible','Visible console body',6,[0,0,0],[0,.08,-.25],['IMG_1634.jpeg']);this.box(leaf,[2.2,.95,.9],[0,.62,0],'light',.08);const monitor=this.group(b,'console-monitor','Monitor',5,[0,0,0],[0,.35,-.2],['IMG_1634.jpeg']);const screen=this.group(monitor,'console-screen','Main screen',6,[0,0,0],[0,.3,-.18],['IMG_1634.jpeg']);this.box(screen,[.85,.55,.08],[0,1.45,0],'graphite',.035);}
  auxiliary(){const u=this.group(this.root,'auxiliary','Auxiliary / Peripheral Attachments',2,[0,0,0],[0,.8,-1.1],['IMG_1165.jpeg','IMG_0947.jpeg']);const s=this.group(u,'aux-hoses','Visible hoses & utility lines',3,[3.55,0,0],[.2,.4,-.5],['IMG_1165.jpeg']);const b=this.group(s,'aux-hose-block','Hose block',4,[0,0,0],[.15,.3,-.4],['IMG_1165.jpeg']);const p=this.group(b,'aux-hose-line','Visible hose line',5,[0,0,0],[.1,.2,-.3],['IMG_1165.jpeg']);const l=this.group(p,'aux-hose-specific','Specific visible hose',6,[0,0,0],[.08,.15,-.25],['IMG_1165.jpeg']);this.tube(l,[[0,1.25,-.95],[.18,1.05,-1.02],[.12,.78,-.98],[.28,.62,-.92]],.045,'rubber');}

  resolvePart(object){let p=object;while(p&&p!==this.root){if(p.userData.selectable)return p;p=p.parent;}return null;}
  contains(parent,node){for(let p=node;p;p=p.parent)if(p===parent)return true;return false;}
  explode(t,selected=null){const amount=THREE.MathUtils.clamp(Number(t)||0,0,1);for(const n of this.nodes)n.position.copy(n.userData.rest);const children=selected?.children.filter(c=>c.userData.selectable);const targets=selected?(children.length?children:[selected]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,amount);this.root.updateMatrixWorld(true);}
  highlight(part){for(const m of this.meshes){m.material.emissive.setHex(part&&this.contains(part,m)?0x174b47:0x000000);m.material.emissiveIntensity=.28;}}
  ghost(on,except=null){this.ghosted=on;for(const m of this.meshes){const faded=on&&(!except||!this.contains(except,m)),glass=m.material.color.getHex()===this.palette.glass;m.material.transparent=faded||glass;m.material.opacity=faded?.17:glass?.64:1;m.material.depthWrite=!faded;m.material.needsUpdate=true;}}
  isolate(part,on=true){for(const n of this.nodes)n.visible=!on||!part||this.contains(part,n)||this.contains(n,part);}
  setLow(on){for(const m of this.meshes)if(m.userData.detail)m.visible=!on;}
  reset(){this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);}
  dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();for(const x of this.meshes)if(x.isInstancedMesh)x.dispose();}
}
